### ISSUE TITLE
how to get the raw txt dataset?

### ISSUE THREAD

**Issue by whut2962575697** [mickeystroller/TaxoExpan#1]
Thanks for your great work! But how can i get the raw txt dataset like this?
![image](https://user-images.githubusercontent.com/25346526/82516251-dadda500-9b4c-11ea-86f0-ab2633d4da98.png)

**Comment by mickeysjm** [comment]
Hi, 

You can download the raw dataset from https://docs.microsoft.com/en-us/academic-services/graph/reference-data-schema#fields-of-study

Due to the license issue, I cannot directly provide you the raw dataset. 

Regards,
--Jiaming

**Comment by whut2962575697** [comment]
Thank you very much!
