### ISSUE TITLE
Hello author, I encountered this problem when running, how can I solve it, thank you

### ISSUE THREAD

**Issue by GitHubBoys** [mickeystroller/TaxoExpan#5]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/15064119/161067587-14109583-663a-42f8-b564-9468e1f42caa.png">

**Comment by mickeysjm** [comment]
Can you check the DGL library is of version 0.4.0?

**Comment by GitHubBoys** [comment]
感谢作者的回复，我查询了版本问题似乎解决了。
<img width="804" alt="image" src="https://user-images.githubusercontent.com/15064119/161505479-7d54a3d5-41e0-48e1-adaf-69f3f8a2fffc.png">

**Comment by GitHubBoys** [comment]
> Can you check the DGL library is of version 0.4.0?

Thank you for your reply，I seem to have solved the problem。
https://github.com/dmlc/dgl/issues/1494

**Comment by GitHubBoys** [comment]
> > Can you check the DGL library is of version 0.4.0?
> 
> Thank you for your reply，I seem to have solved the problem。 [dmlc/dgl#1494](https://github.com/dmlc/dgl/issues/1494)

I ran it successfully, but the python version still requires 3.6, 3.7 will report an error。
https://github.com/eliorc/node2vec/issues/22
<img width="913" alt="image" src="https://user-images.githubusercontent.com/15064119/161518979-cd4ba651-d451-4be4-a229-3bf7ff41467d.png">
<img width="603" alt="image" src="https://user-images.githubusercontent.com/15064119/161519043-8dec7f6c-7b2f-45d5-9cf7-727395527bd0.png">
Many thanks to the author
